version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Variables
          command: export VERSION='16.2'

      - run: 
          name: Docker login
          command: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: Docker build and tag
          command: |
            docker build -t barcus/bareos-director:${CIRCLE_BRANCH}-${VERSION}-mysql director-mysql
            #docker build -t barcus/bareos-director:${CIRCLE_BRANCH}-mysql director-mysql
            #docker build -t barcus/bareos-director:${CIRCLE_BRANCH}-pgsql director-pgsql
            #docker build -t barcus/bareos-client:${CIRCLE_BRANCH} client
            #docker build -t barcus/bareos-storage:${CIRCLE_BRANCH} storage
            #docker build -t barcus/bareos-webui:${CIRCLE_BRANCH} webui
            #docker tag barcus/bareos-director:${CIRCLE_BRANCH}-mysql barcus/bareos-director:${CIRCLE_BRANCH}
            #docker tag barcus/bareos-director:${CIRCLE_BRANCH}-mysql barcus/bareos-director:${VERSION}
            #docker tag barcus/bareos-director:${CIRCLE_BRANCH} barcus/bareos-director:${VERSION}
            #docker tag barcus/bareos-client:${CIRCLE_BRANCH} barcus/bareos-client:${VERSION}
            #docker tag barcus/bareos-storage:${CIRCLE_BRANCH} barcus/bareos-storage:${VERSION}
            #docker tag barcus/bareos-webui:${CIRCLE_BRANCH} barcus/bareos-webui:${VERSION}

      #- run:
      #    name: Docker push
      #    command: |
      #      docker push barcus/bareos-director:${CIRCLE_BRANCH}-mysql
      #      docker push barcus/bareos-director:${CIRCLE_BRANCH}-pgsql
      #      docker push barcus/bareos-director:${CIRCLE_BRANCH}
      #      docker push barcus/bareos-director:${VERSION}
      #      docker push barcus/bareos-client:${CIRCLE_BRANCH}
      #      docker push barcus/bareos-client:${VERSION}
      #      docker push barcus/bareos-storage:${CIRCLE_BRANCH}
      #      docker push barcus/bareos-storage:${VERSION}
      #      docker push barcus/bareos-webui:${CIRCLE_BRANCH}
      #      docker push barcus/bareos-webui:${VERSION}
