version: 2.1

executors:
  my-executor:
    machine: true
jobs:
  build: &build
    executor: my-executor
    steps:
      - checkout
      - run:
          name: Docker build Bareos
          command: |
            export TAG="${CIRCLE_BRANCH}-${BASE_IMG}"
            export BAREOS_PATH="${BAREOS_COMP}"
            echo 'export TAG="${CIRCLE_BRANCH}-${BASE_IMG}"' >> $BASH_ENV
            echo 'export BAREOS_PATH="${BAREOS_COMP}"' >> $BASH_ENV

            if [[ -n "$BAREOS_BACKEND" ]]
            then 
              export TAG="${CIRCLE_BRANCH}-${BASE_IMG}-${BAREOS_BACKEND}"
              export BAREOS_PATH="${BAREOS_COMP}-${BAREOS_BACKEND}"
              echo 'export TAG="${CIRCLE_BRANCH}-${BASE_IMG}-${BAREOS_BACKEND}"' >> $BASH_ENV
              echo 'export BAREOS_PATH="${BAREOS_COMP}-${BAREOS_BACKEND}"' >> $BASH_ENV
            fi
            docker build -t barcus/bareos-${BAREOS_COMP}:${TAG} ${BAREOS_PATH}/$BASE_IMG
      - run:
          name: Save images
          command: |
            mkdir images
            echo "1 ${BAREOS_PATH} - 2 ${BAREOS_COMP} - 3 ${TAG}"
            docker save -o images/image-${BAREOS_PATH}.tar barcus/bareos-${BAREOS_COMP}:${TAG}
      - persist_to_workspace:
          root: .
          paths:
            - ./images

  deploy: &deploy
    executor: my-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load image and add tags
          command: |
            export TAG="${CIRCLE_BRANCH}-${BASE_IMG}"
            export BAREOS_PATH="${BAREOS_COMP}"
            echo 'export TAG="${CIRCLE_BRANCH}-${BASE_IMG}"' >> $BASH_ENV

            if [[ -n "$BAREOS_BACKEND" ]]
            then
              export TAG="${CIRCLE_BRANCH}-${BASE_IMG}-${BAREOS_BACKEND}"
              export BAREOS_PATH="${BAREOS_COMP}-${BAREOS_BACKEND}"
              echo 'export TAG="${CIRCLE_BRANCH}-${BASE_IMG}-${BAREOS_BACKEND}"' >> $BASH_ENV
            fi

            docker load -i /tmp/workspace/images/image-${BAREOS_PATH}.tar
            docker tag barcus/bareos-${BAREOS_COMP}:${TAG} barcus/bareos-${BAREOS_COMP}:${CIRCLE_BRANCH}
      - run: 
          name: Docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Docker push
          command: |
            docker push barcus/bareos-${BAREOS_COMP}:${CIRCLE_BRANCH}
            docker push barcus/bareos-${BAREOS_COMP}:${TAG}

  deploy_client:
    executor: my-executor
    <<: *deploy
      environment:
      - BAREOS_COMP: client
      - BASE_IMG: ubuntu
    

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - deploy_client
      #- build:
      #    name: Build Bareos director-mysql Ubuntu
      #    context: director-ubuntu-mysql
      #- build:
      #    name: Build Bareos director-pgsql Ubuntu
      #    context: director-ubuntu-pgsql
      #- build:
      #    name: Build Bareos client Ubuntu
      #    context: client-ubuntu
      #- build:
      #    name: Build Bareos storage Ubuntu
      #    context: storage-ubuntu
      #- build:
      #    name: Build Bareos webui Ubuntu
      #    context: webui-ubuntu
      #- deploy:
      #    name: Deploy Bareos director-mysql Ubuntu
      #    context: director-ubuntu-mysql
      #    requires:
      #      - Build Bareos director-mysql Ubuntu
      #- deploy:
      #    name: Deploy Bareos director-pgsql Ubuntu
      #    context: director-ubuntu-pgsql
      #    requires:
      #      - Build Bareos director-pgsql Ubuntu
      #- deploy:
      #    name: Deploy Bareos client Ubuntu
      #    context: client-ubuntu
      #    requires:
      #      - Build Bareos client Ubuntu
      #- deploy:
      #    name: Deploy Bareos storage Ubuntu
      #    context: storage-ubuntu
      #    requires:
      #      - Build Bareos webui Ubuntu
      #- deploy:
      #    name: Deploy Bareos webui Ubuntu
      #    context: webui-ubuntu
      #    requires:
      #      - Build Bareos webui Ubuntu
