version: 2.1

executors:
  my-executor:
    machine: true
    working_directory: /tmp

jobs:
  build:
    executor: my-executor
    steps:
      - run:
          name: Set variables
          command: |
            VERSION=$(echo "${CIRCRLE_BRANCH}" | cut -d'-' -f1)
            BASE=$(echo "${CIRCRLE_BRANCH}" | cut -d'-' -f2)
            echo "export VERSION=${VERSION}" >> $BASH_ENV
            echo "export BASE=${BASE}" >> $BASH_ENV
      - run: 
          name: Docker login
          command: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
    
  build-director:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: Docker build and tag
          command: |
            docker build -t barcus/bareos-director:${CIRCLE_BRANCH}-mysql director-mysql
            docker tag barcus/bareos-director:${CIRCLE_BRANCH}-mysql barcus/bareos-director:${CIRCLE_BRANCH}
            docker tag barcus/bareos-director:${CIRCLE_BRANCH}-mysql barcus/bareos-director:${VERSION}

  deploy:
    executor: my-executor
    steps:
      - run:
          name: Docker push
          command: |
            docker push barcus/bareos-director:${CIRCLE_BRANCH}-mysql
            docker push barcus/bareos-director:${CIRCLE_BRANCH}
            docker push barcus/bareos-director:${VERSION}

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - build-director:
          requires:
            - build
      - deploy:
          requires:
            - build-director
      
