version: 2.1

executors:
  my-executor:
    machine: true
jobs:
  build:
    executor: my-executor
    steps:
      - run:
          name: Set variables
          command: |
            VERSION=$(echo "${CIRCRLE_BRANCH}" | cut -d'-' -f1)
            BASE=$(echo "${CIRCRLE_BRANCH}" | cut -d'-' -f2)
            echo "export VERSION=${VERSION}" >> $BASH_ENV
            echo "export BASE=${BASE}" >> $BASH_ENV
    
  build-director:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: Docker build Bareos director
          command: |
            docker build -t barcus/bareos-director:${CIRCLE_BRANCH}-mysql director-mysql
            docker build -t barcus/bareos-director:${CIRCLE_BRANCH}-pgsql director-pgsql
      - run:
          name: Save images
          command: |
            docker save -o image-director-mysql.tar barcus/bareos-director:${CIRCLE_BRANCH}-mysql
            docker save -o image-director-pgsql.tar barcus/bareos-director:${CIRCLE_BRANCH}-pgsql
      - persist_to_workspace:
          root: .
          paths:
            - ./image-director-mysql.tar
            - ./image-director-pgsql.tar

  build-client:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: Docker build Bareos client
          command: |
            docker build -t barcus/bareos-client:${CIRCLE_BRANCH} client
      - run:
          name: Save images
          command: |
            docker save -o image-client.tar barcus/bareos-client:${CIRCLE_BRANCH}
      - persist_to_workspace:
          root: .
          paths:
            - ./image-client.tar

  build-storage:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: Docker build Bareos storage
          command: |
            docker build -t barcus/bareos-storage:${CIRCLE_BRANCH} storage
      - run:
          name: Save images
          command: |
            docker save -o image-storage.tar barcus/bareos-storage:${CIRCLE_BRANCH}
      - persist_to_workspace:
          root: .
          paths:
            - ./image-storage.tar

  build-webui:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: Docker build Bareos webui
          command: |
            docker build -t barcus/bareos-webui:${CIRCLE_BRANCH} webui
      - run:
          name: Save image
          command: |
            docker save -o image-webui.tar barcus/bareos-webui:${CIRCLE_BRANCH}
      - persist_to_workspace:
          root: .
          paths:
            - ./image-webui.tar

  deploy:
    executor: my-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load images and add tags
          command: |
            docker load -i /tmp/workspace/image-director-mysql.tar
            docker load -i /tmp/workspace/image-director-pgsql.tar
            docker load -i /tmp/workspace/image-client.tar
            docker load -i /tmp/workspace/image-storage.tar
            docker load -i /tmp/workspace/image-webui.tar
            docker tag barcus/bareos-director:${CIRCLE_BRANCH}-mysql barcus/bareos-director:${CIRCLE_BRANCH}
            #docker tag barcus/bareos-client:${CIRCLE_BRANCH} barcus/bareos-director:${VERSION}
            #docker tag barcus/bareos-director:${CIRCLE_BRANCH}-mysql barcus/bareos-director:${VERSION}
      - run: 
          name: Docker login
          command: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

      - run:
          name: Docker push
          command: |
            docker push barcus/bareos-director:${CIRCLE_BRANCH}-mysql
            docker push barcus/bareos-director:${CIRCLE_BRANCH}-pgsql
            docker push barcus/bareos-director:${CIRCLE_BRANCH}
            #docker push barcus/bareos-director:${VERSION}
            docker push barcus/bareos-client:${CIRCLE_BRANCH}
            docker push barcus/bareos-storage:${CIRCLE_BRANCH}
            docker push barcus/bareos-webui:${CIRCLE_BRANCH}

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - build-director:
          requires:
            - build
      - build-client:
          requires:
            - build
      - build-storage:
          requires:
            - build
      - build-webui:
          requires:
            - build
      - deploy:
          requires:
            - build-director
            - build-client
            - build-storage
            - build-webui
