version: 2
jobs:
  build:
    machine: true
    steps:
      - run:
          name: Variables
          command: |
            echo "export VERSION='16.2'" >> $BASH_ENV
      - run: 
          name: Docker login
          command: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
    
  build-director:
    machine: true
    steps:
      - checkout
      - run:
          name: Docker build and tag
          command: |
            docker build -t barcus/bareos-director:${CIRCLE_BRANCH}-mysql director-mysql
            docker tag barcus/bareos-director:${CIRCLE_BRANCH}-mysql barcus/bareos-director:${CIRCLE_BRANCH}

      - run:
          name: Docker push
          command: |
            docker push barcus/bareos-director:${CIRCLE_BRANCH}-mysql
            docker push barcus/bareos-director:${CIRCLE_BRANCH}
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - build-director:
          requires:
            - build
