version: 2.1

executors:
  my-executor:
    machine: true
jobs:
  build:
    executor: my-executor
    steps:
      - run:
          name: Set variables
          command: |
            VERSION=$(echo "${CIRCRLE_BRANCH}" | cut -d'-' -f1)
            BASE=$(echo "${CIRCRLE_BRANCH}" | cut -d'-' -f2)
            echo "export VERSION=${VERSION}" >> $BASH_ENV
            echo "export BASE=${BASE}" >> $BASH_ENV
    
  build-director:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: Docker build and tag
          command: |
            docker build -t barcus/bareos-director:${CIRCLE_BRANCH}-mysql director-mysql
            docker build -t barcus/bareos-director:${CIRCLE_BRANCH}-pgsql director-pgsql
            #docker tag barcus/bareos-director:${CIRCLE_BRANCH}-mysql barcus/bareos-director:${VERSION}
      - run:
          name: Save images
          command: |
            docker save -o ~/image-${CIRCLE_BRANCH}-mysql.tar barcus/bareos-director:${CIRCLE_BRANCH}-mysql
            docker save -o ~/image-${CIRCLE_BRANCH}-pgsql.tar barcus/bareos-director:${CIRCLE_BRANCH}-pgsql
      - persist_to_workspace:
          root: /tmp/images
          paths:
            - ~/image-${CIRCLE_BRANCH}-mysql.tar
            - ~/image-${CIRCLE_BRANCH}-pgsql.tar

  deploy:
    executor: my-executor
    steps:
      - attach_workspace:
          at: /tmp/images
      - run:
          name: Load images and add tags
          command: |
            docker load -i /tmp/images/image-${CIRCLE_BRANCH}-mysql.tar
            docker load -i /tmp/images/image-${CIRCLE_BRANCH}-pgsql.tar
            docker tag barcus/bareos-director:${CIRCLE_BRANCH}-mysql barcus/bareos-director:${CIRCLE_BRANCH}
      - run: 
          name: Docker login
          command: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

      - run:
          name: Docker push
          command: |
            docker push barcus/bareos-director:${CIRCLE_BRANCH}-mysql
            docker push barcus/bareos-director:${CIRCLE_BRANCH}-pgsql
            docker push barcus/bareos-director:${CIRCLE_BRANCH}
            #docker push barcus/bareos-director:${VERSION}

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - build-director:
          requires:
            - build
      - deploy:
          requires:
            - build-director
